export const REGISTER = 'REGISTER';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// signup types
export const LOGIN = 'LOGIN';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const REQUEST_RESET_TOKEN = 'REQUEST_RESET_TOKEN';




export const CAR_DETAILS = "CAR_DETAILS"
export const CAR_DETAILS_FAILURE = "CAR_DETAILS_FAILURE"

export const ALL_CARS_DATA = "ALL_CARS_DATA"
export const ALL_CARS_FAILURE = "ALL_CARS_FAILURE"

export const ALL_ARCHIVED_CARS_DATA = "ALL_ARCHIVED_CARS_DATA"
export const ALL_ARCHIVED_CARS_FAILURE = "ALL_ARCHIVED_CARS_FAILURE"



export const SINGLE_CARS_DATA = "SINGLE_CARS_DATA"
export const SINGLE_CARS_DATAFAILURE = "SINGLE_CARS_DATAFAILURE"
export const RESET_SINGLE_CAR_DATA = 'RESET_SINGLE_CAR_DATA';


export const CAR_RECORDS_DETAILS = "CAR_RECORDS_DETAILS";

export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS";
export const GET_CATEGORY_LIST_FAILURE = "GET_CATEGORY_LIST_FAILURE";

export const LOGOUT = "LOGOUT";


export const CAR_DOCUMENT="CAR_DOCUMENT";
export const CAR_DOCUMENT_FAILURE="CAR_DOCUMENT_FAILURE";
export const CAR_DOCUMENT_LISTING="CAR_DOCUMENT_LISTING";


export const NOTIFICATIONS="NOTIFICATIONS";
export const NOTIFICATIONS_FAILTURE="NOTIFICATIONS_FAILURE";



export const COST_TRACKING_COST_OF_OWNERSHIP="COST_TRACKING_COST_OF_OWNERSHIP"; 
export const COST_TRACKING_TOTAL_COST_BREAKING="COST_TRACKING_TOTAL_COST_BREAKING"; 
export const COST_TRACKING_FAILURE="COST_TRACKING_FAILURE"; 

export const ALL_SUBSCRIPTIONS_DATA = "ALL_SUBSCRIPTIONS_DATA"
export const ALL_SUBSCRIPTIONS_FAILURE = "ALL_SUBSCRIPTIONS_FAILURE"
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
export const PAYMENT_FAILURE = "PAYMENT_FAILURE"


export const USER_PROFILE = "USER_PROFILE"
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE"